name: Publish buildgen to PyPI

on: [workflow_dispatch]
# on: push

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Install uv and set Python version
      # Use the official action from astral-sh
      uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.x'
        # Enable caching of installed packages
        enable-cache: true
        # Define files that control the cache key (e.g., requirements files or pyproject.toml)
        cache-dependency-glob: |
          **/*requirements*.txt
          **/pyproject.toml
          **/uv.lock

    - name: Install dependencies
      # This command installs dependencies listed in your project configuration
      run: uv sync

    - name: Run checks
      # This command installs dependencies listed in your project configuration
      run: make fullcheck

    - name: Build a binary wheel and a source tarball
      run: make build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v5
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish buildgen distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/buildgen  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v6
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distributionto PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  # publish-to-testpypi:
  #   name: Publish Python distribution to TestPyPI
  #   needs:
  #   - build
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: testpypi
  #     url: https://test.pypi.org/p/buildgen

  #   permissions:
  #     id-token: write  # IMPORTANT: mandatory for trusted publishing

  #   steps:
  #   - name: Download all the dists
  #     uses: actions/download-artifact@v6
  #     with:
  #       name: python-package-distributions
  #       path: dist/
  #   - name: Publish distribution to TestPyPI
  #     uses: pypa/gh-action-pypi-publish@release/v1
  #     with:
  #       repository-url: https://test.pypi.org/legacy/
